# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-08 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import submission.models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='op_file',
            field=models.FileField(null=True, upload_to=submission.models.random_op_file_name),
        ),
    ]
