# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-08 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_auto_20180908_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='error_file',
            field=models.FileField(default='submission/error/c23d9e8c-ce0b-434a-bdd8-7055a572fac6.txt', upload_to=''),
        ),
        migrations.AlterField(
            model_name='status',
            name='op_file',
            field=models.FileField(default='submission/output/f0c7bec7-86e7-47e2-aca1-413c2bfefffd.txt', upload_to=''),
        ),
    ]
