# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-08 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_auto_20180908_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='error_file',
            field=models.FileField(default='submission/error/99594dd0-6dba-4697-94cd-c520998aab5f.txt', upload_to=''),
        ),
        migrations.AlterField(
            model_name='status',
            name='op_file',
            field=models.FileField(default='submission/output/27e5615b-a994-4437-856b-2156eec7f35c.txt', upload_to=''),
        ),
    ]
