# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-02 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quescode', models.CharField(max_length=100)),
                ('timelimit', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
