# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-23 11:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ip_file',
            field=models.FileField(blank=True, null=True, upload_to='questions/input', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])]),
        ),
        migrations.AddField(
            model_name='question',
            name='op_file',
            field=models.FileField(blank=True, null=True, upload_to='questions/output', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])]),
        ),
    ]
