# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-23 11:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_auto_20180823_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ip_file',
            field=models.FileField(blank=True, null=True, upload_to='questions/input', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'], message="Please upload '.txt' files only.")]),
        ),
        migrations.AlterField(
            model_name='question',
            name='op_file',
            field=models.FileField(blank=True, null=True, upload_to='questions/output', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'], message="Please upload '.txt' files only.")]),
        ),
    ]
